[changelog]
header = """
# Changelog\n
All notable changes to **Gossamer** are documented here.\n
"""
body = """
{%- set repo_url = "https://github.com/venezia/gossamer" -%}

{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
            {% if commit.breaking %}*(breaking)* {% endif %}\
            {{ commit.message | upper_first }}\
            {% if commit.remote.username %} by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}){% endif %}\
            {% if commit.remote.pr_number %} in \
              [#{{ commit.remote.pr_number }}]({{ repo_url }}/pull/{{ commit.remote.pr_number }}){% endif %}\
             ([{{ commit.id | truncate(length=7, end="") }}]({{ repo_url }}/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}

{%- if github is defined and github.contributors | length != 0 %}

  ---

  ### Contributors

  {% for contributor in github.contributors %}\
    [@{{ contributor.username }}](https://github.com/{{ contributor.username }}){{ " " }}\
  {% endfor %}
{% endif -%}

"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
filter_commits = true
tag_pattern = "v[0-9].*"
sort_commits = "oldest"

commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^test", group = "Testing" },
    { message = "^ci", group = "CI/CD" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps\\)", group = "Dependencies" },
    { message = "^chore", group = "Chores" },
    { message = "^build", group = "CI/CD" },
    { message = "^revert", group = "Reverts" },
]

link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/venezia/gossamer/issues/$1" },
]

[bump]
initial_tag = "v0.1.0"
