{{- if .Values.credentials.truenasTokens }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gossamer.fullname" . }}-truenas
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gossamer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.credentials.truenasTokens }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.credentials.ipmiCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gossamer.fullname" . }}-ipmi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gossamer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.credentials.ipmiCredentials }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
